### ISSUE TITLE
Is there some documentation about the CH552T used to configure FPGA ?

### ISSUE THREAD

**Issue by Martoni** [sipeed/Tang-Nano-Doc#2]
As I see on schematic, to transfert the bitstream, a microcontroller CH552T is used.
Is there some documentation on this part ? Is there some firmware code or other think ?

**Comment by lucapuano** [comment]
Yo Martoni, I'm not a Sipeed's engineer or something else but I'm working also on the schematic of a custom Sipeed Maixduino to create my own board and I searched some information about the CH552T because i also need it

There is the datasheet of the CH552T at this link:
https://datasheet.lcsc.com/szlcsc/1810010214_WCH-Jiangsu-Qin-Heng-CH552T_C111367.pdf

I also found on the database of Sipeed's project some useful files, like the firmware used on the maixduino board:
http://dl.sipeed.com/MAIX/factory_firmware/ch552

I don't know if the schematic of the CH552T part is the same as mine, but I think that might be useful to you. If you have some information that could be useful please answer me.

**Comment by kprasadvnsi** [comment]
You can get an English datasheet from here: https://github.com/Blinkinlabs/ch554_sdcc/blob/master/documentation/CH554%20manual%20english.pdf

Source code for CH552 used in Tang Nano board is posted here: https://github.com/diodep/ch55x_jtag

**Comment by Martoni** [comment]
thanks @kprasadvnsi, it will be usefull for [openFPGALoader](https://github.com/trabucayre/openFPGALoader) to configure tang nano.
